INFO 2025-01-17 09:20:55,130 kevm_pyk.summarizer - Number of opcodes: 84
INFO 2025-01-17 09:20:55,130 kevm_pyk.summarizer - Number of passed opcodes: 77
INFO 2025-01-17 09:20:55,130 kevm_pyk.summarizer - Number of todo opcodes: 7
INFO 2025-01-17 09:20:55,130 kevm_pyk.summarizer - Todo opcodes: ['CREATE', 'CALL', 'CALLCODE', 'DELEGATECALL', 'CREATE2', 'STATICCALL', 'SELFDESTRUCT']
INFO 2025-01-17 09:20:55,130 kevm_pyk.__main__ - summarizing ['CREATE', 'CALL', 'CALLCODE', 'DELEGATECALL', 'CREATE2', 'STATICCALL', 'SELFDESTRUCT']
INFO 2025-01-17 09:20:55,130 pyk.kast.outer - Loading JSON definition: /home/zhaoji/.cache/kdist-9ffc41e/evm-semantics/haskell/compiled.json
INFO 2025-01-17 09:20:55,255 pyk.kast.outer - Converting JSON definition to Kast: /home/zhaoji/.cache/kdist-9ffc41e/evm-semantics/haskell/compiled.json
INFO 2025-01-17 09:20:55,752 pyk.utils - Making directory: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/kcfg
INFO 2025-01-17 09:20:55,753 pyk.utils - Making directory: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/kcfg/nodes
INFO 2025-01-17 09:20:55,756 kevm_pyk.summarizer - Setting the type of `ID_CELL` to `Int` for CALL
INFO 2025-01-17 09:20:55,756 kevm_pyk.summarizer - Setting more concrete `ACCOUNTS_CELL` for CALL
INFO 2025-01-17 09:20:55,756 kevm_pyk.summarizer - Setting constraints on `ACCOUNTS_CELL` for CALL
INFO 2025-01-17 09:20:55,757 pyk.kore.rpc - Starting KoreServer: kore-rpc-booster /home/zhaoji/.cache/kdist-9ffc41e/evm-semantics/haskell/definition.kore --module EDSL --server-port 0 --llvm-backend-library /home/zhaoji/.cache/kdist-9ffc41e/evm-semantics/haskell/llvm-library/interpreter.so --interim-simplification 25
INFO 2025-01-17 09:20:55,764 pyk.kore.rpc - [PID=3398501][stde] [proxy] Loading definition from /home/zhaoji/.cache/kdist-9ffc41e/evm-semantics/haskell/definition.kore, main module "EDSL"
INFO 2025-01-17 09:20:56,765 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Reading the input file TimeSpec {sec = 0, nsec = 24810680}
INFO 2025-01-17 09:20:57,766 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Parsing the file TimeSpec {sec = 0, nsec = 120}
INFO 2025-01-17 09:20:58,767 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Verifying the definition TimeSpec {sec = 0, nsec = 221}
INFO 2025-01-17 09:20:59,768 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Executing TimeSpec {sec = 0, nsec = 720595978}
INFO 2025-01-17 09:20:59,768 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Reading the input file TimeSpec {sec = 0, nsec = 26673906}
INFO 2025-01-17 09:20:59,768 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Parsing the file TimeSpec {sec = 0, nsec = 130}
INFO 2025-01-17 09:21:00,736 pyk.kore.rpc - KoreServer started: 0.0.0.0:36581, pid=3398501
INFO 2025-01-17 09:21:00,736 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:00,736 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:00,737 kevm_pyk.utils - Computing definedness constraint for initial node: CALL_7_SPEC
INFO 2025-01-17 09:21:00,764 pyk.kore.rpc - Sending request to localhost:36581: 140087848072656-001 - simplify
INFO 2025-01-17 09:21:00,769 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848072656-001
INFO 2025-01-17 09:21:00,769 pyk.kore.rpc - [PID=3398501][stde] [kore][info] Verifying the definition TimeSpec {sec = 0, nsec = 211}
INFO 2025-01-17 09:21:00,769 pyk.kore.rpc - [PID=3398501][stde] [proxy] Starting RPC server
INFO 2025-01-17 09:21:01,345 pyk.kore.rpc - Received response from localhost:36581: 140087848072656-001 - simplify
INFO 2025-01-17 09:21:01,361 pyk.kore.rpc - Sending request to localhost:36581: 140087848072656-002 - simplify
INFO 2025-01-17 09:21:01,770 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848072656-002
INFO 2025-01-17 09:21:02,032 pyk.kore.rpc - Received response from localhost:36581: 140087848072656-002 - simplify
INFO 2025-01-17 09:21:02,032 kevm_pyk.utils - Simplifying initial and target node: CALL_7_SPEC
INFO 2025-01-17 09:21:02,044 pyk.kore.rpc - Sending request to localhost:36581: 140087848072656-003 - simplify
INFO 2025-01-17 09:21:02,652 pyk.kore.rpc - Received response from localhost:36581: 140087848072656-003 - simplify
INFO 2025-01-17 09:21:02,665 pyk.kore.rpc - Sending request to localhost:36581: 140087848072656-004 - simplify
INFO 2025-01-17 09:21:02,771 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848072656-004
INFO 2025-01-17 09:21:02,772 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848072656-003
INFO 2025-01-17 09:21:03,235 pyk.kore.rpc - Received response from localhost:36581: 140087848072656-004 - simplify
INFO 2025-01-17 09:21:03,241 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:03,243 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:03,244 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:03,244 pyk.proof.proof - [ZJH] prover type: <class 'pyk.proof.reachability.APRProver'>
INFO 2025-01-17 09:21:03,244 pyk.proof.reachability - [ZJH] init proof
INFO 2025-01-17 09:21:03,253 pyk.kore.rpc - Sending request to localhost:36581: 140087848117008-001 - add-module
INFO 2025-01-17 09:21:03,773 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848117008-001
INFO 2025-01-17 09:21:04,067 pyk.kore.rpc - Received response from localhost:36581: 140087848117008-001 - add-module
INFO 2025-01-17 09:21:04,098 pyk.kore.rpc - Sending request to localhost:36581: 140087848117008-002 - add-module
INFO 2025-01-17 09:21:04,774 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848117008-002
INFO 2025-01-17 09:21:04,972 pyk.kore.rpc - Received response from localhost:36581: 140087848117008-002 - add-module
INFO 2025-01-17 09:21:04,973 pyk.proof.reachability - [ZJH] pending: [1]
INFO 2025-01-17 09:21:04,973 pyk.proof.reachability - [ZJH] node_id: 1
INFO 2025-01-17 09:21:04,974 pyk.proof.reachability - [ZJH] is_terminal: False
INFO 2025-01-17 09:21:04,974 pyk.proof.reachability - [ZJH] node_id: 2
INFO 2025-01-17 09:21:04,974 pyk.proof.reachability - [ZJH] is_terminal: False
INFO 2025-01-17 09:21:04,974 pyk.proof.reachability - [ZJH] pending: [1]
INFO 2025-01-17 09:21:04,975 pyk.proof.proof - [ZJH] proof initialized
INFO 2025-01-17 09:21:04,975 pyk.proof.proof - [ZJH] pending: [1]
INFO 2025-01-17 09:21:04,975 pyk.proof.reachability - Before appending step: 1
INFO 2025-01-17 09:21:04,975 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:04,975 pyk.proof.proof - Submitted steps for proof: CALL_7_SPEC
INFO 2025-01-17 09:21:04,976 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:05,007 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-001 - implies
INFO 2025-01-17 09:21:05,569 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-001 - implies
INFO 2025-01-17 09:21:05,577 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:05,577 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:05,577 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-002 - execute
INFO 2025-01-17 09:21:05,775 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-001
INFO 2025-01-17 09:21:05,775 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-002
INFO 2025-01-17 09:21:09,602 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-002 - execute
INFO 2025-01-17 09:21:09,604 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:09,604 pyk.kore.rpc - [zjh] [kore-client] logs: []
INFO 2025-01-17 09:21:09,627 pyk.kcfg.kcfg - Extending current KCFG with the following: 2 branches: 1 --> [3, 4]: ['notBool STATIC_CELL:Bool andBool #changesState ( CALL , W0:Int : W1:Int : W2:Int : W3:Int : W4:Int : W5:Int : W6:Int : WS:WordStack )', '#changesState ( CALL , W0:Int : W1:Int : W2:Int : W3:Int : W4:Int : W5:Int : W6:Int : WS:WordStack ) andBool STATIC_CELL:Bool']
INFO 2025-01-17 09:21:09,627 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:09,629 pyk.proof.reachability - Before appending step: 3
INFO 2025-01-17 09:21:09,629 pyk.proof.reachability - Before appending step: 4
INFO 2025-01-17 09:21:09,635 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:09,660 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:09,661 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-003 - implies
INFO 2025-01-17 09:21:09,705 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-001 - implies
INFO 2025-01-17 09:21:09,743 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-003
INFO 2025-01-17 09:21:10,366 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-003 - implies
INFO 2025-01-17 09:21:10,375 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:10,375 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:10,376 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-004 - execute
INFO 2025-01-17 09:21:10,385 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-001 - implies
INFO 2025-01-17 09:21:10,395 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:10,395 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:10,395 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-002 - execute
INFO 2025-01-17 09:21:10,744 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-001
INFO 2025-01-17 09:21:10,744 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-004
INFO 2025-01-17 09:21:10,744 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-002
INFO 2025-01-17 09:21:13,985 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-004 - execute
INFO 2025-01-17 09:21:13,986 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:13,986 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'a49bbf5c4b82ee9c477b266571ac6462951ccd1a83f52cbf657b2c60368c2c04'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '5434057e141b2cefb82ee7bd640b8951b997a28d3fe1259a551bcd0a539e2500'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e172045eb84cf6e9e9f715bf9702837e2b925f4d87316504b0eebaaf57a71908'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:21:14,007 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 3: 3 --> 5
INFO 2025-01-17 09:21:14,007 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:14,009 pyk.proof.reachability - Before appending step: 4
INFO 2025-01-17 09:21:14,009 pyk.proof.reachability - Before appending step: 5
INFO 2025-01-17 09:21:14,041 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-005 - implies
INFO 2025-01-17 09:21:14,043 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-005
INFO 2025-01-17 09:21:14,755 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-005 - implies
INFO 2025-01-17 09:21:14,765 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:14,765 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:14,765 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-006 - execute
INFO 2025-01-17 09:21:15,044 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-006
INFO 2025-01-17 09:21:18,053 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-002 - execute
INFO 2025-01-17 09:21:18,058 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:18,058 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '1bff66964f5b20d29393ded3392d56b94df96b1ed92b4dc6f0300126e8575d02'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7c6df1b7a841ef7cce64eaae0c332bb9383a2692d649e88e8ea49fcb7fa5d540'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:21:18,087 pyk.kcfg.explore - [zjh] next_node_logs: ()
INFO 2025-01-17 09:21:18,088 pyk.kcfg.explore - [zjh] rules: []
INFO 2025-01-17 09:21:18,088 pyk.kcfg.explore - [zjh] _log_succ_rewrites: True
INFO 2025-01-17 09:21:18,089 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 2: 4 --> 6
INFO 2025-01-17 09:21:18,089 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:18,090 pyk.proof.reachability - Before appending step: 5
INFO 2025-01-17 09:21:18,091 pyk.proof.reachability - Before appending step: 6
INFO 2025-01-17 09:21:18,092 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:18,093 pyk.proof.reachability - Before appending step: 5
INFO 2025-01-17 09:21:18,348 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-006 - execute
INFO 2025-01-17 09:21:18,350 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:18,350 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:21:18,366 pyk.kcfg.kcfg - Extending current KCFG with the following: 2 branches: 5 --> [7, 8]: ['USEGAS_CELL:Bool', 'notBool USEGAS_CELL:Bool']
INFO 2025-01-17 09:21:18,367 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:18,371 pyk.proof.reachability - Before appending step: 7
INFO 2025-01-17 09:21:18,371 pyk.proof.reachability - Before appending step: 8
INFO 2025-01-17 09:21:18,464 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-003 - implies
INFO 2025-01-17 09:21:18,464 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-007 - implies
INFO 2025-01-17 09:21:18,467 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-007
INFO 2025-01-17 09:21:19,142 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-003 - implies
INFO 2025-01-17 09:21:19,152 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:19,152 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:19,152 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-004 - execute
INFO 2025-01-17 09:21:19,165 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-007 - implies
INFO 2025-01-17 09:21:19,182 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:19,182 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:19,183 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-008 - execute
INFO 2025-01-17 09:21:19,468 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-008
INFO 2025-01-17 09:21:19,468 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-004
INFO 2025-01-17 09:21:19,468 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-003
INFO 2025-01-17 09:21:24,483 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-008 - execute
INFO 2025-01-17 09:21:24,485 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:24,485 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'kore-rpc', 'result': {'tag': 'success', 'rule-id': '9940b671074c218a6c5f0f9e7b90d05efbcc000ee2884306b43860e14f6979e4'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '6df8fdf9e7eb75ead383f8ad6ab5900fa638d6cf0cac2ea969d09d6cbea088bf'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4c9b1cb59f30bf1f56514ef0a94e6f6fc0b1b912033c03daa96ad2926a249e55'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '8d25e554cb0a8de20bfb6b22391cf5f0e702a84f7eff1bd0264e0f0d95ca2dba'}}]
INFO 2025-01-17 09:21:24,497 pyk.proof.reachability - Caching next step for edge starting from 8
INFO 2025-01-17 09:21:24,499 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 4: 8 --> 9
INFO 2025-01-17 09:21:24,499 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:24,503 pyk.proof.reachability - Before appending step: 7
INFO 2025-01-17 09:21:24,503 pyk.proof.reachability - Before appending step: 9
INFO 2025-01-17 09:21:24,536 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-009 - implies
INFO 2025-01-17 09:21:24,538 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-009
INFO 2025-01-17 09:21:25,304 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-009 - implies
INFO 2025-01-17 09:21:25,306 pyk.proof.reachability - Using cached step for edge 8 --> 9
INFO 2025-01-17 09:21:25,310 pyk.kcfg.kcfg - Extending current KCFG with the following: 2 branches: 9 --> [10, 11]: ['BALANCE_CELL:Int <Int W2:Int', 'W2:Int <=Int BALANCE_CELL:Int']
INFO 2025-01-17 09:21:25,311 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:25,314 pyk.proof.reachability - Before appending step: 7
INFO 2025-01-17 09:21:25,314 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:25,314 pyk.proof.reachability - Before appending step: 11
INFO 2025-01-17 09:21:25,320 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:25,345 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:25,347 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-010 - implies
INFO 2025-01-17 09:21:25,453 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-001 - implies
INFO 2025-01-17 09:21:25,540 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-010
INFO 2025-01-17 09:21:25,540 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-001
INFO 2025-01-17 09:21:26,147 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-010 - implies
INFO 2025-01-17 09:21:26,157 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:26,157 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:26,158 pyk.kore.rpc - Sending request to localhost:36581: 140087848356048-011 - execute
INFO 2025-01-17 09:21:26,158 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-001 - implies
INFO 2025-01-17 09:21:26,168 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:26,168 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:26,168 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-002 - execute
INFO 2025-01-17 09:21:26,544 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-002
INFO 2025-01-17 09:21:26,544 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848356048-011
INFO 2025-01-17 09:21:27,182 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-004 - execute
INFO 2025-01-17 09:21:27,183 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:27,184 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'kore-rpc', 'result': {'tag': 'success', 'rule-id': 'add363ff9fa24e9a97a4cad5848a44dce9315dd67365b44dd01db1cc969472f1'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '0ecc38b7234d7c0cade4244e22e4386ff1bb0c372d5f2b7f556686fe7c765ac8'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '56113c99a0230d88a2a58bc6170978dfe457a677437498c1a01061de40aff083'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '93bd0f294cb595b34c16df4e98d6937113aa642a3c3f149c2cb10849d807debd'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about the remainder after applying a rule', 'rule-id': 'a0a224658695b9eeae4eecf43289c46f78c5b34020e5e6ef966eaaf80525eccf'}}]
INFO 2025-01-17 09:21:27,202 pyk.proof.reachability - Caching next step for edge starting from 7
INFO 2025-01-17 09:21:27,203 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 4: 7 --> 12
INFO 2025-01-17 09:21:27,204 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:27,206 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:27,207 pyk.proof.reachability - Before appending step: 11
INFO 2025-01-17 09:21:27,207 pyk.proof.reachability - Before appending step: 12
INFO 2025-01-17 09:21:27,240 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-005 - implies
INFO 2025-01-17 09:21:27,546 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-005
INFO 2025-01-17 09:21:28,022 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-005 - implies
INFO 2025-01-17 09:21:28,025 pyk.proof.reachability - Using cached step for edge 7 --> 12
INFO 2025-01-17 09:21:28,029 pyk.kcfg.kcfg - Extending current KCFG with the following: 2 branches: 12 --> [13, 14]: ['Cmem ( SCHEDULE_CELL:Schedule , #memoryUsageUpdate ( #memoryUsageUpdate ( MEMORYUSED_CELL:Int , W3:Int , W4:Int ) , W5:Int , W6:Int ) ) -Int Cmem ( SCHEDULE_CELL:Schedule , MEMORYUSED_CELL:Int ) <=Gas GAS_CELL:Gas', 'GAS_CELL:Gas <Gas Cmem ( SCHEDULE_CELL:Schedule , #memoryUsageUpdate ( #memoryUsageUpdate ( MEMORYUSED_CELL:Int , W3:Int , W4:Int ) , W5:Int , W6:Int ) ) -Int Cmem ( SCHEDULE_CELL:Schedule , MEMORYUSED_CELL:Int )']
INFO 2025-01-17 09:21:28,030 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:28,033 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:28,034 pyk.proof.reachability - Before appending step: 11
INFO 2025-01-17 09:21:28,034 pyk.proof.reachability - Before appending step: 13
INFO 2025-01-17 09:21:28,034 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:28,040 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:28,065 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:28,068 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-006 - implies
INFO 2025-01-17 09:21:28,103 pyk.kore.rpc - Sending request to localhost:36581: 140087844250256-001 - implies
INFO 2025-01-17 09:21:28,548 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087844250256-001
INFO 2025-01-17 09:21:28,548 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-006
INFO 2025-01-17 09:21:29,579 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-006 - implies
INFO 2025-01-17 09:21:29,592 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:29,592 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:29,592 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-007 - execute
INFO 2025-01-17 09:21:29,594 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-007
INFO 2025-01-17 09:21:29,751 pyk.kore.rpc - Received response from localhost:36581: 140087844250256-001 - implies
INFO 2025-01-17 09:21:29,763 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:29,763 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:29,763 pyk.kore.rpc - Sending request to localhost:36581: 140087844250256-002 - execute
INFO 2025-01-17 09:21:30,313 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-002 - execute
INFO 2025-01-17 09:21:30,315 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:30,315 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '95592308c533ccc4249823006b453dd57cbf6b44b15e65f2e17ec12c01f8d273'}}]
INFO 2025-01-17 09:21:30,332 pyk.proof.reachability - Caching next step for edge starting from 11
INFO 2025-01-17 09:21:30,333 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 1: 11 --> 15
INFO 2025-01-17 09:21:30,334 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:30,336 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:30,337 pyk.proof.reachability - Before appending step: 13
INFO 2025-01-17 09:21:30,337 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:30,337 pyk.proof.reachability - Before appending step: 15
INFO 2025-01-17 09:21:30,370 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-003 - implies
INFO 2025-01-17 09:21:30,597 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087844250256-002
INFO 2025-01-17 09:21:30,597 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-003
INFO 2025-01-17 09:21:31,191 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-003 - implies
INFO 2025-01-17 09:21:31,194 pyk.proof.reachability - Using cached step for edge 11 --> 15
INFO 2025-01-17 09:21:31,198 pyk.kcfg.kcfg - Extending current KCFG with the following: 2 branches: 15 --> [16, 17]: ['CALLDEPTH_CELL:Int <Int 1024', '1024 <=Int CALLDEPTH_CELL:Int']
INFO 2025-01-17 09:21:31,198 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:31,203 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:31,203 pyk.proof.reachability - Before appending step: 13
INFO 2025-01-17 09:21:31,203 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:31,203 pyk.proof.reachability - Before appending step: 16
INFO 2025-01-17 09:21:31,203 pyk.proof.reachability - Before appending step: 17
INFO 2025-01-17 09:21:31,209 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:31,235 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:31,238 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-004 - implies
INFO 2025-01-17 09:21:31,271 pyk.kore.rpc - Sending request to localhost:36581: 140087848402640-001 - implies
INFO 2025-01-17 09:21:31,598 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-004
INFO 2025-01-17 09:21:31,598 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848402640-001
INFO 2025-01-17 09:21:32,060 pyk.kore.rpc - Received response from localhost:36581: 140087848402640-001 - implies
INFO 2025-01-17 09:21:32,071 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:32,071 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:32,071 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-004 - implies
INFO 2025-01-17 09:21:32,072 pyk.kore.rpc - Sending request to localhost:36581: 140087848402640-002 - execute
INFO 2025-01-17 09:21:32,081 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:32,082 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:32,082 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-005 - execute
INFO 2025-01-17 09:21:32,635 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087848402640-002
INFO 2025-01-17 09:21:32,635 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-005
INFO 2025-01-17 09:21:38,507 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-005 - execute
INFO 2025-01-17 09:21:38,510 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:38,510 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '6562921549bec1cce23131cdc3562a3518d8de45416806cd4987ba71b6399a5c'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '21754df4d86c493b2f3f4dbbc43fa3f09d015426a79120c2f77e05a90e6da2d0'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '21754df4d86c493b2f3f4dbbc43fa3f09d015426a79120c2f77e05a90e6da2d0'}}]
INFO 2025-01-17 09:21:38,532 pyk.proof.reachability - Caching next step for edge starting from 16
INFO 2025-01-17 09:21:38,533 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 1: 16 --> 18
INFO 2025-01-17 09:21:38,533 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:38,537 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:38,537 pyk.proof.reachability - Before appending step: 13
INFO 2025-01-17 09:21:38,538 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:38,538 pyk.proof.reachability - Before appending step: 17
INFO 2025-01-17 09:21:38,538 pyk.proof.reachability - Before appending step: 18
INFO 2025-01-17 09:21:38,572 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-006 - implies
INFO 2025-01-17 09:21:38,574 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-006
INFO 2025-01-17 09:21:38,931 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-007 - execute
INFO 2025-01-17 09:21:39,042 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:39,042 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e80dae2349dc4cf016147f969cff262399d625e3e979474e412b3c14914c4e77'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '858e480d252334ee5df36fb446d3a1c0273f543cd8cce906d5480997378b8af8'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'f3fae1eaa5efa7cf21ef25008fecf88e0ce9fb08df5efcfd3c10446640ba715e'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'd6eabd1c8c90cc47dc22c91e42557e93c8c6a1fc55793c80e17c72e37df36f2e'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}]
INFO 2025-01-17 09:21:39,070 pyk.proof.reachability - Caching next step for edge starting from 13
INFO 2025-01-17 09:21:39,072 pyk.kcfg.kcfg - Extending current KCFG with the following: basic block at depth 4: 13 --> 19
INFO 2025-01-17 09:21:39,072 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:39,076 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:39,076 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:39,076 pyk.proof.reachability - Before appending step: 17
INFO 2025-01-17 09:21:39,077 pyk.proof.reachability - Before appending step: 18
INFO 2025-01-17 09:21:39,077 pyk.proof.reachability - Before appending step: 19
INFO 2025-01-17 09:21:39,114 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-008 - implies
INFO 2025-01-17 09:21:39,479 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-006 - implies
INFO 2025-01-17 09:21:39,481 pyk.proof.reachability - Using cached step for edge 16 --> 18
INFO 2025-01-17 09:21:39,487 pyk.kcfg.kcfg - Extending current KCFG with the following: 3 branches: 18 --> [20, 21, 22]: ['notBool <acctID>\n  W1:Int modInt pow160\n</acctID> in_keys ( DotAccountVar:AccountCellMap ) andBool CODE_CELL:AccountCode ==K CODE:Bytes andBool ID_CELL:Int ==Int W1:Int modInt pow160', 'notBool <acctID>\n  W1:Int modInt pow160\n</acctID> in_keys ( AC1_1:AccountCellMap ) andBool notBool <acctID>\n  ID_CELL:Int\n</acctID> in_keys ( AC1_1:AccountCellMap ) andBool notBool ID_CELL:Int ==Int W1:Int modInt pow160 andBool DotAccountVar:AccountCellMap ==K <account>\n  <acctID>\n    W1:Int modInt pow160\n  </acctID>\n  _Gen0:BalanceCell\n  <code>\n    CODE:Bytes\n  </code>\n  _Gen1:StorageCell\n  _Gen2:OrigStorageCell\n  _Gen3:TransientStorageCell\n  _Gen4:NonceCell\n</account> AC1_1:AccountCellMap', 'true']
INFO 2025-01-17 09:21:39,488 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:39,495 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:39,495 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:39,495 pyk.proof.reachability - Before appending step: 17
INFO 2025-01-17 09:21:39,495 pyk.proof.reachability - Before appending step: 19
INFO 2025-01-17 09:21:39,496 pyk.proof.reachability - Before appending step: 20
INFO 2025-01-17 09:21:39,496 pyk.proof.reachability - Before appending step: 21
INFO 2025-01-17 09:21:39,496 pyk.proof.reachability - Before appending step: 22
INFO 2025-01-17 09:21:39,502 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:39,513 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:39,528 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:39,532 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-007 - implies
INFO 2025-01-17 09:21:39,537 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:39,584 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-007
INFO 2025-01-17 09:21:39,589 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-008
INFO 2025-01-17 09:21:39,595 pyk.kore.rpc - Sending request to localhost:36581: 140087842302544-001 - implies
INFO 2025-01-17 09:21:39,604 pyk.kore.rpc - Sending request to localhost:36581: 140087842296272-001 - implies
INFO 2025-01-17 09:21:40,577 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087842302544-001
INFO 2025-01-17 09:21:40,577 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087842296272-001
INFO 2025-01-17 09:21:40,685 pyk.kore.rpc - Received response from localhost:36581: 140087842296272-001 - implies
INFO 2025-01-17 09:21:40,696 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:40,696 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:40,696 pyk.kore.rpc - Sending request to localhost:36581: 140087842296272-002 - execute
INFO 2025-01-17 09:21:41,009 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-008 - implies
INFO 2025-01-17 09:21:41,013 pyk.proof.reachability - Using cached step for edge 13 --> 19
INFO 2025-01-17 09:21:41,021 pyk.kcfg.kcfg - Extending current KCFG with the following: 3 branches: 19 --> [23, 24, 25]: ['notBool <acctID>\n  W1:Int modInt pow160\n</acctID> in_keys ( DotAccountVar:AccountCellMap ) andBool ID_CELL:Int ==Int W1:Int modInt pow160', 'notBool <acctID>\n  W1:Int modInt pow160\n</acctID> in_keys ( AC1_1:AccountCellMap ) andBool notBool <acctID>\n  ID_CELL:Int\n</acctID> in_keys ( AC1_1:AccountCellMap ) andBool notBool ID_CELL:Int ==Int W1:Int modInt pow160 andBool DotAccountVar:AccountCellMap ==K <account>\n  <acctID>\n    W1:Int modInt pow160\n  </acctID>\n  <balance>\n    BAL:Int\n  </balance>\n  <code>\n    CODE:AccountCode\n  </code>\n  _Gen0:StorageCell\n  _Gen1:OrigStorageCell\n  _Gen2:TransientStorageCell\n  <nonce>\n    NONCE:Int\n  </nonce>\n</account> AC1_1:AccountCellMap', 'true']
INFO 2025-01-17 09:21:41,022 pyk.proof.reachability - Wrote proof data for CALL_7_SPEC: /home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/proofs/CALL_7_SPEC/proof.json
INFO 2025-01-17 09:21:41,030 pyk.proof.reachability - Before appending step: 10
INFO 2025-01-17 09:21:41,030 pyk.proof.reachability - Before appending step: 14
INFO 2025-01-17 09:21:41,031 pyk.proof.reachability - Before appending step: 17
INFO 2025-01-17 09:21:41,035 pyk.proof.reachability - Before appending step: 20
INFO 2025-01-17 09:21:41,035 pyk.proof.reachability - Before appending step: 21
INFO 2025-01-17 09:21:41,035 pyk.proof.reachability - Before appending step: 22
INFO 2025-01-17 09:21:41,036 pyk.proof.reachability - Before appending step: 23
INFO 2025-01-17 09:21:41,036 pyk.proof.reachability - Before appending step: 24
INFO 2025-01-17 09:21:41,036 pyk.proof.reachability - Before appending step: 25
INFO 2025-01-17 09:21:41,058 pyk.kore.rpc - Connecting to host: localhost:36581
INFO 2025-01-17 09:21:41,076 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-009 - implies
INFO 2025-01-17 09:21:41,076 pyk.kore.rpc - Connected to host: localhost:36581
INFO 2025-01-17 09:21:41,114 pyk.kore.rpc - Sending request to localhost:36581: 140087844058896-001 - implies
INFO 2025-01-17 09:21:41,115 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-007 - implies
INFO 2025-01-17 09:21:41,125 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:41,125 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:41,126 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-008 - execute
INFO 2025-01-17 09:21:41,274 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-008 - execute
INFO 2025-01-17 09:21:41,312 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-009 - implies
INFO 2025-01-17 09:21:41,578 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-008
INFO 2025-01-17 09:21:41,578 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-009
INFO 2025-01-17 09:21:41,578 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-009
INFO 2025-01-17 09:21:41,578 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087844058896-001
INFO 2025-01-17 09:21:41,578 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087842296272-002
INFO 2025-01-17 09:21:42,073 pyk.kore.rpc - Received response from localhost:36581: 140087842302544-001 - implies
INFO 2025-01-17 09:21:42,085 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:42,085 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:42,086 pyk.kore.rpc - Sending request to localhost:36581: 140087842302544-002 - execute
INFO 2025-01-17 09:21:42,595 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087842302544-002
INFO 2025-01-17 09:21:44,245 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-009 - implies
INFO 2025-01-17 09:21:44,259 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:44,259 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:44,260 pyk.kore.rpc - Sending request to localhost:36581: 140087846632272-010 - execute
INFO 2025-01-17 09:21:44,264 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087846632272-010
INFO 2025-01-17 09:21:44,912 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-009 - implies
INFO 2025-01-17 09:21:44,930 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:44,930 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:44,931 pyk.kore.rpc - Sending request to localhost:36581: 140087845559440-010 - execute
INFO 2025-01-17 09:21:45,266 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087845559440-010
INFO 2025-01-17 09:21:45,738 pyk.kore.rpc - Received response from localhost:36581: 140087844058896-001 - implies
INFO 2025-01-17 09:21:45,755 pyk.kore.rpc - [zjh] [kore-client] log-successful-rewrites: True
INFO 2025-01-17 09:21:45,766 pyk.kore.rpc - [zjh] [kore-client] log-failed-rewrites: True
INFO 2025-01-17 09:21:45,767 pyk.kore.rpc - Sending request to localhost:36581: 140087844058896-002 - execute
INFO 2025-01-17 09:21:46,273 pyk.kore.rpc - [PID=3398501][stde] [proxy] Processing request 140087844058896-002
INFO 2025-01-17 09:21:53,151 pyk.kore.rpc - Received response from localhost:36581: 140087842296272-002 - execute
INFO 2025-01-17 09:21:53,154 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:53,154 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '21754df4d86c493b2f3f4dbbc43fa3f09d015426a79120c2f77e05a90e6da2d0'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '21754df4d86c493b2f3f4dbbc43fa3f09d015426a79120c2f77e05a90e6da2d0'}}]
INFO 2025-01-17 09:21:59,534 pyk.kore.rpc - Received response from localhost:36581: 140087846632272-010 - execute
INFO 2025-01-17 09:21:59,538 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:59,538 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}]
INFO 2025-01-17 09:21:59,864 pyk.kore.rpc - Received response from localhost:36581: 140087844250256-002 - execute
INFO 2025-01-17 09:21:59,868 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:21:59,868 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'proxy', 'result': {'tag': 'success', 'rule-id': 'a0a224658695b9eeae4eecf43289c46f78c5b34020e5e6ef966eaaf80525eccf'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7c6df1b7a841ef7cce64eaae0c332bb9383a2692d649e88e8ea49fcb7fa5d540'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:21:59,903 pyk.kcfg.explore - [zjh] next_node_logs: ()
INFO 2025-01-17 09:21:59,903 pyk.kcfg.explore - [zjh] rules: []
INFO 2025-01-17 09:21:59,903 pyk.kcfg.explore - [zjh] _log_succ_rewrites: True
INFO 2025-01-17 09:21:59,903 pyk.proof.reachability - Caching next step for edge starting from 14
INFO 2025-01-17 09:22:01,929 pyk.kore.rpc - Received response from localhost:36581: 140087845559440-010 - execute
INFO 2025-01-17 09:22:01,933 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:22:01,933 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e79d5eb2c563bd6b5a0e134360cb94695f8cb8a5474220b0f89b063f1277373e'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4df6cfa533509bc8bd81d7220e5f6ba3029d355df456c8cbad16a8945b744673'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '54581daf165a5ab7cce9d1772244d5a380d9a1d33b458cf66b4ed8be99828cab'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '99f939dd781281a3ce1f0231f4f49225da3211c2c0e533300e352e79b316220f'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '02ddfe807601eecb8cc3041a06b19fe63c1a5f7ea2e144d7d3400fe9e7eb2469'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '046eae744d1abba9fee03326639bda446eb3ef3cf61b2b9bc734ccc11bcfb439'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about the remainder after applying a rule', 'rule-id': 'a0a224658695b9eeae4eecf43289c46f78c5b34020e5e6ef966eaaf80525eccf'}}]
INFO 2025-01-17 09:22:01,963 pyk.proof.reachability - Caching next step for edge starting from 23
INFO 2025-01-17 09:22:02,167 pyk.kore.rpc - Received response from localhost:36581: 140087842302544-002 - execute
INFO 2025-01-17 09:22:02,171 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:22:02,171 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '21754df4d86c493b2f3f4dbbc43fa3f09d015426a79120c2f77e05a90e6da2d0'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '9755450bde476dd9f827d984eaca12750da526bbe8c15856a31e3277645ef24d'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7367325bf2741c1f8d5cd9d51f4f679d49c2f41aed04d42d8918bc28b771c761'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'ab82e81bcc6d44a158477b3a150d83c6c77b9df6e9633fc8576d1944d3f6d9c1'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '0fd8560a0508fab0223c1816c24799417f82ff54f64cda426b08c60ad3445f20'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about unification of rule', 'rule-id': '0fd8560a0508fab0223c1816c24799417f82ff54f64cda426b08c60ad3445f20'}}, {'tag': 'rewrite', 'origin': 'kore-rpc', 'result': {'tag': 'success', 'rule-id': 'e90470d0eb62f90b49efec43b661acc09cdf2aec23e74cf9830dd3e69043b2f5'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e9079f8b8bb6350a1003f08341aa798f800d1b992d8d3ae135573e524d5de726'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'b6fd2c6cd34fbc46306e5ef9640296d2170ea7899f8e637084754de2b6a539f5'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '123a5d1b446cf62313d336b264e95bac4219293090cdc45e4635372ce5779063'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '123a5d1b446cf62313d336b264e95bac4219293090cdc45e4635372ce5779063'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e0be8be66c732016fc7cd956c7cfe80d7558729ed9ef0a8804046b2167ad91f5'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4c9b1cb59f30bf1f56514ef0a94e6f6fc0b1b912033c03daa96ad2926a249e55'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4c9b1cb59f30bf1f56514ef0a94e6f6fc0b1b912033c03daa96ad2926a249e55'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3ed83064ce067eb3adeb4c1ff9097c7d91305bec82a9d4818dd9a266961f0598'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '62a302145f4cba0115e2d8a5b30474f3588f436ee576bf7bca891eb95524ff8e'}}]
INFO 2025-01-17 09:22:02,198 pyk.kcfg.explore - [zjh] next_node_logs: ()
INFO 2025-01-17 09:22:02,198 pyk.kcfg.explore - [zjh] rules: []
INFO 2025-01-17 09:22:02,198 pyk.kcfg.explore - [zjh] _log_succ_rewrites: True
INFO 2025-01-17 09:22:02,198 pyk.proof.reachability - Caching next step for edge starting from 21
INFO 2025-01-17 09:22:04,015 pyk.kore.rpc - Received response from localhost:36581: 140087844058896-002 - execute
INFO 2025-01-17 09:22:04,020 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:22:04,020 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'e79d5eb2c563bd6b5a0e134360cb94695f8cb8a5474220b0f89b063f1277373e'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4df6cfa533509bc8bd81d7220e5f6ba3029d355df456c8cbad16a8945b744673'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '54581daf165a5ab7cce9d1772244d5a380d9a1d33b458cf66b4ed8be99828cab'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '99f939dd781281a3ce1f0231f4f49225da3211c2c0e533300e352e79b316220f'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'f2e5e71b6012c35cf4546f6bbf3cbf49db553bfeaa7dc0e0945370ac7c8c02a2'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '02ddfe807601eecb8cc3041a06b19fe63c1a5f7ea2e144d7d3400fe9e7eb2469'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '046eae744d1abba9fee03326639bda446eb3ef3cf61b2b9bc734ccc11bcfb439'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'Uncertain about the remainder after applying a rule', 'rule-id': 'a0a224658695b9eeae4eecf43289c46f78c5b34020e5e6ef966eaaf80525eccf'}}]
INFO 2025-01-17 09:22:04,054 pyk.proof.reachability - Caching next step for edge starting from 24
INFO 2025-01-17 09:29:47,011 pyk.kore.rpc - Received response from localhost:36581: 140087848402640-002 - execute
INFO 2025-01-17 09:29:48,222 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:29:48,222 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '078c8b8ac629764762ac47ab11e6574d31c918a6bf38c4caa6c83ca76a687fea'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4fcc3d576faa9475a655dea14c7c69594485de9810d16b2c3d08626efbc07ffb'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7367325bf2741c1f8d5cd9d51f4f679d49c2f41aed04d42d8918bc28b771c761'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'ab82e81bcc6d44a158477b3a150d83c6c77b9df6e9633fc8576d1944d3f6d9c1'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7c6df1b7a841ef7cce64eaae0c332bb9383a2692d649e88e8ea49fcb7fa5d540'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'a996096166da631587650b9081cd742f00ca1831360df32dae280c2929078608'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'c72f3822ea67a114563c074f9a8ff287dd44197ec83cce1b94abc40923119d44'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'b5ec50cc9af567d4ef7587709181e89b4727d2e739325502c50f3bf2fc2702d8'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'cf46a1c55ae03d7124b8c4d35be85667c49f90ee5e2aa9e23faa9190b8e37682'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '27458eb47839269121ea93b912b579bddb9557fccc51e69983d94b2e6ed21335'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:29:51,051 pyk.kcfg.explore - [zjh] next_node_logs: ()
INFO 2025-01-17 09:29:51,051 pyk.kcfg.explore - [zjh] rules: []
INFO 2025-01-17 09:29:51,051 pyk.kcfg.explore - [zjh] _log_succ_rewrites: True
INFO 2025-01-17 09:29:51,053 pyk.proof.reachability - Caching next step for edge starting from 17
INFO 2025-01-17 09:29:53,552 pyk.kore.rpc - Received response from localhost:36581: 140087848356048-011 - execute
INFO 2025-01-17 09:29:54,555 pyk.kore.rpc - [zjh] [kore-client] result: dict_keys(['reason', 'depth', 'state', 'next-states', 'logs'])
INFO 2025-01-17 09:29:54,555 pyk.kore.rpc - [zjh] [kore-client] logs: [{'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '1917662cf7a79a4e167b3fe1b2c28a736001725a4b952713b36ad8bbdc324f4b'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '4fcc3d576faa9475a655dea14c7c69594485de9810d16b2c3d08626efbc07ffb'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7367325bf2741c1f8d5cd9d51f4f679d49c2f41aed04d42d8918bc28b771c761'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'ab82e81bcc6d44a158477b3a150d83c6c77b9df6e9633fc8576d1944d3f6d9c1'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '7c6df1b7a841ef7cce64eaae0c332bb9383a2692d649e88e8ea49fcb7fa5d540'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '3d8b3569577237015e49cc215f5fa1a74dc5cdaa9dddea7123dd1215bd3b0435'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'a996096166da631587650b9081cd742f00ca1831360df32dae280c2929078608'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'c72f3822ea67a114563c074f9a8ff287dd44197ec83cce1b94abc40923119d44'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'b5ec50cc9af567d4ef7587709181e89b4727d2e739325502c50f3bf2fc2702d8'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': 'cf46a1c55ae03d7124b8c4d35be85667c49f90ee5e2aa9e23faa9190b8e37682'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'success', 'rule-id': '27458eb47839269121ea93b912b579bddb9557fccc51e69983d94b2e6ed21335'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}, {'tag': 'rewrite', 'origin': 'booster', 'result': {'tag': 'failure', 'reason': 'No applicable rules found'}}]
INFO 2025-01-17 09:29:57,047 pyk.kcfg.explore - [zjh] next_node_logs: ()
INFO 2025-01-17 09:29:57,047 pyk.kcfg.explore - [zjh] rules: []
INFO 2025-01-17 09:29:57,047 pyk.kcfg.explore - [zjh] _log_succ_rewrites: True
INFO 2025-01-17 09:29:57,050 pyk.proof.reachability - Caching next step for edge starting from 10
ERROR 2025-01-17 09:29:57,050 kevm_pyk.utils - Proof crashed: CALL_7_SPEC
Runtime error | code: -32002 | data: SMT problem: Unexpected result while calling 'check-sat': Error "line 1 column 15732: Sorts SortAccountCode and SortBytes are incompatible"
Traceback (most recent call last):
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 926, in _request
    return self._client.request(method, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 246, in request
    return self._default_client.request(method, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 325, in request
    self._check(data)
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 336, in _check
    raise JsonRpcError(**response['error'])
pyk.kore.rpc.JsonRpcError: Runtime error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zhaoji/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 152, in run_prover
    parallel_advance_proof(
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/proof/proof.py", line 386, in parallel_advance_proof
    proof_results = future.result()
                    ^^^^^^^^^^^^^^^
  File "/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/proof/proof.py", line 465, in step
    return prover.step_proof(proof_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/proof/reachability.py", line 897, in step_proof
    extend_results = self.kcfg_explore.extend_cterm(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kcfg/explore.py", line 231, in extend_cterm
    cterm, next_states, depth, vacuous, next_node_logs = self.cterm_symbolic.execute(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/cterm/symbolic.py", line 110, in execute
    response = self._kore_client.execute(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 990, in execute
    result = self._request('execute', **params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaoji/.cache/pypoetry/virtualenvs/kevm-pyk-9eA2lNH8-py3.11/lib/python3.11/site-packages/pyk/kore/rpc.py", line 928, in _request
    raise self._error(err) from err
pyk.kore.rpc.DefaultError: Runtime error | code: -32002 | data: SMT problem: Unexpected result while calling 'check-sat': Error "line 1 column 15732: Sorts SortAccountCode and SortBytes are incompatible"
INFO 2025-01-17 09:29:57,053 pyk.kore.rpc - Stopping KoreServer: 0.0.0.0:36581, pid=3398501
INFO 2025-01-17 09:29:57,161 pyk.kore.rpc - KoreServer stopped: 0.0.0.0:36581, pid=3398501
Proof timing CALL_7_SPEC: 533.9180297851562s
